apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservices-frontend
  name: microservices-frontend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: microservices-frontend
