apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: microservices-users
  name: microservices-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-users
  template:
    metadata:
      labels:
        app: microservices-users
        service: microservices-users
    spec:
      containers:
      - name: microservices-users
        image: insaneall/microservices-users
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
