apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feed
  name: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        image: insaneall/microservices-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"             
        ports:
        - containerPort: 8080


